AxfProject/AxfProject/urls.py
# 导入相关的包
from django.conf.urls import url, include
from django.contrib import admin

# 注册路由，将将相关路由分配交给app来完成
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/',include('axf.urls',namespace='axf')),
]

AxfProject/axf/urls.py
from django.conf.urls import url
from axf import views

urlpatterns = [
    url(r'^home/',views.home,name='home'),
    url(r'^market/',views.market,name='market'),
    url(r'^mine/',views.mine,name='mine'),
    url(r'^cart/',views.cart,name='cart'),
    # 传递参数的方式
    url(r'^marketname/(\d+)/(\d+)/(\d+)',views.marketCategory,name='marketCategory'),
    url(r'^login/',views.login,name='login'),
    url(r'^dologin/',views.dologin,name='dologin'),
    url(r'^register/',views.register,name='register'),
    url(r'^doregister/',views.doregister,name='doregister'),
    url(r'^checkuser/',views.checkuser,name='checkuser'),
    url(r'^checklogin/',views.checklogin,name='checklogin'),
    url(r'^logout/',views.logout,name='logout'),
    url(r'^dellcart/',views.dellcart,name='dellcart'),
    url(r'^goodadd/(\d+)',views.goodadd,name='goodadd'),
    url(r'^goodsub/(\d+)',views.goodsub,name='goodsub'),
    url(r'^register_two',views.register_two,name='register_two'),
    url(r'^doregister_two/',views.doregister_tow,name='doregister_two'),
    url(r'^checkuser_two/',views.checkuser_two,name='checkuser_two'),
    url(r'^cart02/', views.cart02, name='cart02'),
    url(r'^delgoods/',views.delgoods,name='delgoods'),
]

AxfProject/axf/models.py
from django.db import models

# Create your models here.
# 首页轮播数据
class Wheel(models.Model):
    img = models.CharField(max_length=150)
    name = models.CharField(max_length=20)
    trackid = models.CharField(max_length=20)
# 首页导航数据
class Nav(models.Model):
    img = models.CharField(max_length=150)
    name = models.CharField(max_length=20)
    trackid = models.CharField(max_length=20)
# 首页小轮播
class Mustbuy(models.Model):
    img = models.CharField(max_length=150)
    name = models.CharField(max_length=20)
    trackid = models.CharField(max_length=20)
# 首页便利店 块等数据
class Shop(models.Model):
    img = models.CharField(max_length=150)
    name = models.CharField(max_length=20)
    trackid = models.CharField(max_length=20)
# 主要信息
class MainShow(models.Model):
    trackid = models.CharField(max_length=10)
    name = models.CharField(max_length=20)
    img = models.CharField(max_length=100)
    categoryid = models.CharField(max_length=10)
    brandname = models.CharField(max_length=20)

    img1 = models.CharField(max_length=100)
    childcid1 = models.CharField(max_length=10)
    productid1 = models.CharField(max_length=10)
    longname1 = models.CharField(max_length=50)
    price1 = models.CharField(max_length=10)
    marketprice1 = models.CharField(max_length=10)

    img2 = models.CharField(max_length=100)
    childcid2 = models.CharField(max_length=10)
    productid2 = models.CharField(max_length=10)
    longname2 = models.CharField(max_length=50)
    price2 = models.CharField(max_length=10)
    marketprice2 = models.CharField(max_length=10)

    img3 = models.CharField(max_length=100)
    childcid3 = models.CharField(max_length=10)
    productid3 = models.CharField(max_length=10)
    longname3 = models.CharField(max_length=50)
    price3 = models.CharField(max_length=10)
    marketprice3 = models.CharField(max_length=10)

# 分类模型
class FoodTypes(models.Model):
    typeid = models.CharField(max_length=10)
    typename = models.CharField(max_length=20)
    typesort = models.IntegerField()
    childtypenames = models.CharField(max_length=150)
# 商品模型类
class Goods(models.Model):
    # 商品id
    productid = models.CharField(max_length=10)
    # 商品图片
    productimg = models.CharField(max_length=150)
    # 商品名称
    productname = models.CharField(max_length=50)
    # 商品长名称
    productlongname = models.CharField(max_length=100)
    # 是否精选
    isxf = models.NullBooleanField(default=False)
    # 是否买一赠一
    pmdesc = models.CharField(max_length=10)
    # 规格
    specifics = models.CharField(max_length=20)
    # 价格
    price = models.CharField(max_length=10)
    # 超市价格
    marketprice = models.CharField(max_length=10)
    # 组id
    categoryid = models.CharField(max_length=10)
    # 子类组id
    childcid = models.CharField(max_length=10)
    # 子类组名称
    childcidname = models.CharField(max_length=10)
    # 详情页id
    dealerid = models.CharField(max_length=10)
    # 库存
    storenums = models.IntegerField()
    # 销量
    productnum = models.IntegerField()
    # 购买者



# 简易用户模型
class userinfo(models.Model):
    # 用户账户 要唯一性
    useraccount = models.CharField(max_length=20,unique=True)
    # 密码
    upassword = models.CharField(max_length=300)
    # 昵称
    username = models.CharField(max_length=20)
    # 手机号
    userphone = models.CharField(max_length=20)
    #用户地址
    useradderss = models.CharField(max_length=200,null=False)  #这里的null=False就是默认使当前字段为空
# 这个是错误的
class cart(models.Model):
    userccount = models.CharField(max_length=20)
    usergoods = models.CharField(max_length=20)
# 购物车1.0版本
class NewCart(models.Model):
    nccount = models.CharField(max_length=20)
    ngoodsid = models.CharField(max_length=20)
# 购物车2.0版本
class TwoCart(models.Model):
    tccount = models.CharField(max_length=20)
    tgoodid = models.CharField(max_length=20)
    # 新增数量字段
    tgoodnum = models.IntegerField()
# 购物车3.0版本
class Xcart(models.Model):
    tccount = models.CharField(max_length=20)
    tgoodid = models.ForeignKey(Goods)
    # 新增数量字段
    tgoodnum = models.IntegerField()

AxfProject/axf/views.py
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.shortcuts import render

# Create your views here.
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from axf.models import Wheel, Nav, Mustbuy, Shop, MainShow, FoodTypes, Goods, userinfo, NewCart, TwoCart, Xcart
# 导入密码加密模块
import hashlib

# 打开主页
def home(request):
    wheels = Wheel.objects.all()
    navs = Nav.objects.all()
    mustbuys = Mustbuy.objects.all()
    shop = Shop.objects.all()
    shop1 = shop[0]
    shop2 = shop[1:3]
    shop3 = shop[3:7]
    shop4 = shop[7:11]
    maininfos = MainShow.objects.all()
    # print(maininfos)
    context = {'pageTitle':'主页','wheels':wheels,'musbuys':mustbuys,
               'navs':navs,'shop1':shop1,'shop2':shop2,'shop3':shop3,'shop4':shop4,
               'maininfos':maininfos,
               }

    return render(request,'axf/Home.html',context)

# 因为在基础模板中使用里一种方法 因此这个方法已经失效了
def market(request):
    # 获取所有商品类型
    typenames = FoodTypes.objects.all()
    # 获取刚开始进入时显示的数据
    goodlist = Goods.objects.all().filter(categoryid=104749)
    context = {'pagetitle':'闪送','typenames':typenames,'goodlist':goodlist,}
    # return render(request,'axf/Market.html',context)
    return HttpResponseRedirect(reverse('axf:marketCategory')) #重定向

def marketCategory(request,foodtype,childcid,ordering):
    # 获取所有商品类型
    typenames = FoodTypes.objects.all()
    if ordering =='0':
        orderRule ='id'
    elif ordering =='1':
        orderRule = 'price'
    elif ordering =='2':
        orderRule = '-price'
    elif ordering =='3':
        orderRule = 'storenums'
    else:
        orderRule = 'id'
    if childcid =='0':
        goodlist = Goods.objects.all().filter(categoryid=foodtype).order_by(orderRule)
    else:
        goodlist = Goods.objects.all().filter(categoryid=foodtype).filter(childcid=childcid).order_by(orderRule)
    # 获取显示的数据
    foodtype = int(foodtype)
    # 获取分类的名字
    type = FoodTypes.objects.filter(typeid=foodtype).first()
    # 测试获取数据
    # print(type.childtypenames)
    typename = type.childtypenames
    childtypeandnames = typename.split('#')
    items = []
    for child in childtypeandnames:
    #     分割列表中的每一项 并放在字典里 然后在存在列表里
        childs = child.split(':')
        item = {'childName':childs[0],'childTypeId':childs[1]}
        items.append(item)
        # print(item)
    context = {'pagetitle':'闪送','typenames': typenames, 'goodlist': goodlist,
               'items':items,'foodtypeid':foodtype,'orderRule':ordering,'childcid':childcid}
    return render(request, 'axf/Market.html', context)
# 个人中心
def mine(request):
    try:
        username = request.session.get('username','未登录')
    except KeyError:
        pass
    context = {'pagetitle':'我的','username':username}
    return render(request,'axf/Mine.html',context)

# 点击登录时跳转
def login(request):
    return render(request,'axf/Login.html')
# 执行登录操作
def dologin(request):
    uccount = request.POST.get('useraccount')
    upawd = request.POST.get('upassword')
    if userinfo.objects.all().filter(useraccount=uccount).first():
        print('得到数据')
        user = userinfo.objects.all().filter(useraccount=uccount).first()
        # if user.upassword ==upawd:
    else:
        print('没有得到数据')
    request.session['uccount'] = uccount
    response = HttpResponseRedirect(reverse('axf:mine'))
    return response

# 点击注册时跳转
def register(request):
    return render(request,'axf/Register.html')
# 执行注册,就是保存注册的内容
def doregister(request):
    uccount = request.POST.get('useraccount')
    upawd = request.POST.get('upassword')
    uname = request.POST.get('username')
    uphone = request.POST.get('userphone')
    user = userinfo()
    user.useraccount = uccount
    user.upassword = upawd
    user.username = uname
    user.userphone = uphone
    user.save()
    response = HttpResponseRedirect(reverse('axf:register'))
    return response
# 购物车 并判断是否有账号登录
def cart(request):
    username = request.session.get('username',)
    myuserccount = request.session.get('uccount',)
    if not username:
        # print('没有获取到session数据')
        return render(request, 'axf/qregister.html')
    else:
        # print(username)
        # print(myuserccount)
        # ##########################在这里要准备进行购物车的操作
        # ugoodobjs = NewCart.objects.all().filter(nccount=myuserccount)
        # 购物车2.0
        # ugoodobjs = TwoCart.objects.all().filter(tccount=myuserccount)
        # ugoodsidlist = []
        # ugoodnumdic = {}
        # for ugoodobj in ugoodobjs:
        #     # 获得id
        #     myugoodid = ugoodobj.tgoodid
        #     myugoodobj = Goods.objects.all().filter(id=myugoodid).first()
        #     myugoodnumobj = TwoCart.objects.all().filter(tgoodid=myugoodid).first()
        #     # 获得对应数量
        #     myugoodnum = myugoodnumobj.tgoodnum
        #     ugoodnumdic[myugoodid] = myugoodnum
        #     # ugoodnumlist.append(myugoodnum)
        #     ugoodsidlist.append(myugoodobj)
        # print(ugoodsidlist)  #得到所有的用户添加的商品，但是其中有重复的，需要考虑解决方案
        # print(ugoodnumdic)
        # context = {'ugoods':ugoodsidlist,'ugoodnum':ugoodnumdic}
        # 购物车3.0
        ugoodobjs = Xcart.objects.all().filter(tccount=myuserccount)
        context = {'ugoods': ugoodobjs}
        return render(request,'axf/cart02.html',context)

# 检查用户名是否可注册，这里是一个异步请求时发生的函数
# 当失去焦点时就进行一个异步请求，请求数据是否合理
def checkuser(request):
    precheck = request.GET.get('useraccount')
    print(precheck)
    prechecknum = userinfo.objects.all().filter(useraccount=precheck).first()
    print(prechecknum)
    if not prechecknum:
        context = {'status': '用户名可用'}
        print(context)
    else:
        context = {'status': '用户名已经存在'}
        print('不可以注册，用户名存在')
    return JsonResponse(context)
#检查登录
def checklogin(request):
    checkuaccount = request.GET.get('useraccount')
    checkupawd = request.GET.get('upassword')
    checknum = userinfo.objects.all().filter(useraccount=checkuaccount).first()
    if checknum:
        userobj = userinfo.objects.all().filter(useraccount=checkuaccount).first()
        # print(userobj.upassword)
        # 1.创建一个hash对象
        h = hashlib.sha256()
        # 2.填充要加密的数据
        h.update(bytes(checkupawd, encoding='utf-8'))
        # 3.获取加密结果
        checkresult = h.hexdigest()
        if userobj.upassword == str(checkupawd) or userobj.upassword == str(checkresult):
            # 这个时候应该弹出一个框 登录成功然后跳转到个人中心
            # 也要设置cookie或者session
            username = userobj.username
            uccount = userobj.useraccount
            # 获取用户账号并为购物车存储一个关键session
            request.session['uccount'] = uccount
            request.session['username'] = username
            context = {'status':''}
        else:
            context = {'status': '用户密码错误'}
    else:
        # print('not')
        context = {'status': '用户名不存在'}
    return JsonResponse(context)

#检查购物车，这一步是在添加购物车的时候进行的操作，进行了Ajax请求
def dellcart(request):
    # 已经获取到了用户 和添加的 商品id
    goodid = request.GET.get('goodid')
    uccount = request.session.get('uccount')
    # print(uccount)
    if not uccount:
        # print(uccount)
        # 检查是否登录，没登录时会提示登录
        mycontext = {'status': 'error'}
    else:
        # print(goodid, uccount)
        goodid = str(goodid)
        uccount = str(uccount)
        # 存储购物车 1.0版本
        # newcart = NewCart()
        # newcart.nccount = uccount
        # newcart.ngoodsid = goodid
        # newcart.save()
        # 存储购物车2.0版本
        # twocart = TwoCart()
        # checkgood = TwoCart.objects.all().filter(tccount=uccount).filter(tgoodid=goodid).first()
        # 购物车3.0版本
        twocart = Xcart()
        checkgood = Xcart.objects.all().filter(tccount=uccount).filter(tgoodid__id=goodid).first()
        if not checkgood:
            goodobj = Goods.objects.all().filter(id=goodid).first()
            # print(checkgood)
            twocart.tccount = uccount
            twocart.tgoodid = goodobj
            twocart.tgoodnum = 1
            twocart.save()
        else:
            # print('第二次你才会看到我')
            checkgood.tgoodnum += 1
            checkgood.save()
        mycontext = {'status': 'ok'}
    return JsonResponse(mycontext)

# 退出按钮
def logout(request):
    try:
        del request.session['username']
        del request.session['uccount']
    except KeyError:
        pass
    return render(request,'axf/logout.html')

# 购买数量加一
def goodadd(request,goodid):
    uccount = request.session.get('uccount')
    goodaddobj = Xcart.objects.all().filter(tgoodid__id=goodid).filter(tccount=uccount).first()
    goodaddobj.tgoodnum += 1
    goodaddobj.save()
    return HttpResponseRedirect(reverse('axf:cart'))

# 购买数量减一
def goodsub(request,goodid):
    uccount = request.session.get('uccount')
    goodaddobj = Xcart.objects.all().filter(tgoodid__id=goodid).filter(tccount=uccount).first()
    if goodaddobj.tgoodnum <= 1:
        pass
    else:
        goodaddobj.tgoodnum -= 1
        goodaddobj.save()
    return HttpResponseRedirect(reverse('axf:cart'))

# 用户注册2.0版本
def register_two(request):
    return render(request,'axf/Register-two.html')

def doregister_tow(request):
    uccount = request.POST.get('useraccount')
    upawd = request.POST.get('upassword')
    uname = request.POST.get('username')
    uphone = request.POST.get('userphone')
    h = hashlib.sha256()
    h.update(bytes(upawd,encoding='utf-8'))
    pawdresult = h.hexdigest()
    user = userinfo()
    user.useraccount = uccount
    user.upassword = pawdresult
    user.username = uname
    user.userphone = uphone
    user.save()
    response = HttpResponseRedirect(reverse('axf:login'))
    return response

def checkuser_two(request):
    precheck = request.GET.get('useraccount')
    print(precheck)
    prechecknum = userinfo.objects.all().filter(useraccount=precheck).first()
    print(prechecknum)
    if not prechecknum:
        context = {'status': '用户名可用'}
        print(context)
    else:
        context = {'status': '用户名已经存在'}
        print('不可以注册，用户名存在')
    return JsonResponse(context)

AxfProject/templates/axf/Cart.html
{% extends 'axf/Base.html' %}
{% load static %}
{% block personResource %}
    <link rel="stylesheet" href="{% static 'cart/css/cart.css' %}">
    <script type="text/javascript" src="{% static 'base/js/jquery.js' %}"></script>
    <script type="text/javascript">
        $(function () {
{#            $('.cartcontent').click(function () {#}
{#                var myp = $(this).children('.mynum')#}
{#                mynum = myp.html()#}
{#                console.log(mynum)#}
{#                if (mynum == 1) {#}
{#                    var mya = $(this).children('a').children('.mycartleft')#}
{#                    var myval = mya.html()#}
{#                    console.log(myval)#}
{#                    mya.css('background','#ccc')#}
{#                }#}
{#            })#}
            $('.mycartleft').click(function () {
                var myp = $(this).parent()
                var myn = myp.next().html()
                console.log(myn)
                if (myn == 1) {
                    $(this).css('background','#ccc');
                }
            })
        })
    </script>
{% endblock %}
{% block content %}
    <div class="contents">
        <div class="mycontent">
            {% for ugood in ugoods %}
                <div class="cartgoods">
                    <div class="uleft"><img src="{{ ugood.tgoodid.productimg }}"></div>
                    <div class="uright">
                        <p>{{ ugood.tgoodid.productname }}</p>
                        <p>￥：{{ ugood.tgoodid.price }}</p>
                    </div>
                    <div class="cartcontent">
                        <a href="{% url 'axf:goodsub' ugood.tgoodid.id %}"><div class="mycartleft">-</div></a>
                        <div class="mynum">{{ ugood.tgoodnum }}</div>
                        <a href="{% url 'axf:goodadd' ugood.tgoodid.id %}"><div class="mycartright">+</div></a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

AxfProject/templates/axf/Mine.html
{% extends 'axf/Base.html' %}
{% load static %}
{% block personResource %}
    <link rel="stylesheet" href="{% static 'mine/css/mine.css' %}">
    <script type="text/javascript" charset="utf-8" src="{% static 'mine/js/mine.js' %}"></script>

{% endblock %}
{% block content %}
<div id="mine">
    <section class="fixed">
		<span class="glyphicon glyphicon-user"></span>
		<p><a href="{% url 'axf:login' %}">{{username}}</a></p>
		<p><span class="glyphicon glyphicon-fire"></span><span>等级</span></p>
		<a id="regis" href="{% url 'axf:register_two' %}">注册</a>
		<p><span class="glyphicon glyphicon-heart"></span>商品收藏</p>
	</section>

    <section class="mine">
		<p>
			<span>我的订单</span><a>查看全部订单&gt;</a>
		</p>
		<nav id="nav">
			<ul>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-usd"></span></dt>
							<dd>代付款</dd>
						</dl>
					</a>
				</li>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-envelope"></span></dt>
							<dd>待收货</dd>
						</dl>
					</a>
				</li>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-pencil"></span></dt>
							<dd>待评价</dd>
						</dl>
					</a>
				</li>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-retweet"></span></dt>
							<dd>退款/售后</dd>
						</dl>
					</a>
				</li>
			</ul>
		</nav>


		<menu>
			<ul>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-bullhorn"></span></dt>
							<dd>积分商城</dd>
						</dl>
					</a>
				</li>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-credit-card"></span></dt>
							<dd>优惠券</dd>
						</dl>
					</a>
				</li>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-import"></span></dt>
							<dd>收货地址</dd>
						</dl>
					</a>
				</li>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-phone-alt"></span></dt>
							<dd>客服/反馈</dd>
						</dl>
					</a>
				</li>
				<li>
					<a>
						<dl>
							<dt><span class="glyphicon glyphicon-asterisk"></span></dt>
							<dd>关于我们</dd>
						</dl>
					</a>
				</li>
			</ul>
		</menu>
		<p><a href="{% url 'axf:logout' %}">退出当前账号</a></p>
	</section>
</div>
{% endblock %}

AxfProject/templates/axf/cart02.html
{% extends 'axf/Base.html' %}
{% load static %}
{% block personResource %}
    <link rel="stylesheet" href="{% static 'cart02/css/cart.css' %}">
    {#    <script type="text/javascript" src="{% static 'base/js/jquery.js' %}"></script>#}
    <script type="text/javascript">
        $(function () {
            {#            获取删除这个按钮#}
            var mydel = $('.mydel');
            {#            自定义的函数,用来处理选择价钱的#}

            function myfunc(allimg) {
                var mylen = allimg.length;
                var j = 0;
                var sum = 0;
                for (var i = 0; i < mylen; i++) {
                    var needtwo = allimg[i];
                    var needthree = needtwo.attributes['0'].nodeValue;
                    if (needthree == '/static/base/img/round_select.png') {
                        j++;
                        var myneedd = allimg[i].parentElement.parentElement.parentElement;
                        var myneeddd = myneedd.children;
                        var testprice = (myneeddd[1].children)[1].innerHTML;
                        var price = testprice.substring(2);
                        var testnum = (myneeddd[2].children)[1].innerHTML;
                        var myprice = Number(price) * Number(testnum);
                        sum = sum + myprice
                    }
                }
                var myprice = $('.myprece');
                myprice[0].innerHTML = sum.toFixed(2);
                if (j == mylen) {
                    $('.myleft').children('img').attr('src', '/static/base/img/round_select.png');
                }
                if (j == 0) {
                    mydel.css('color', '#ccc');
                }
            }

            {#            处理获取所有商品ID的函数#}

            function getgoodid(allimg) {
                var mylen = allimg.length;
                var arr = new Array();
                for (var i = 0; i < mylen; i++) {
                    var needtwo = allimg[i];
                    var needthree = needtwo.attributes['0'].nodeValue;
                    if (needthree == '/static/base/img/round_select.png') {
                        var mypar = allimg[i].parentElement;
                        var myid = (mypar.children)[1].innerHTML;
                        arr.push(Number(myid));
                    }
                }
                {#                测试是否成功#}
                {#                console.log(arr);#}
                return arr
            }

            {#            目的是为了当数量为一时就不能再次点击，变成灰色#}
            $('.mycartleft').click(function () {
                var myp = $(this).parent();
                var myn = myp.next().html();
                console.log(myn);
                if (myn == 1) {
                    $(this).css('background', '#ccc');
                }
            });
            {#            按钮点击事件#}
            $('.usleft').click(function () {
                var myimg = $(this).children('img');
                var allimg = $('.usleft').children('img');
                if (myimg.attr('src') == '/static/base/img/round.png') {
                    myimg.attr('src', '/static/base/img/round_select.png');
                    var allimg = $('.usleft').children('img');
                    myfunc(allimg);
                    mydel.css('color', 'black');
                } else {
                    myimg.attr('src', '/static/base/img/round.png');
                    $('.myleft').children('img').attr('src', '/static/base/img/round.png');
                    var allimg = $('.usleft').children('img');
                    myfunc(allimg);
                }
            });
            {#            全选按钮事件#}
            $('.myleft').click(function () {
                var allimg = $('.usleft').children('img');
                var onesrue = $(this).children('img');
                if (onesrue.attr('src') == '/static/base/img/round.png') {
                    onesrue.attr('src', '/static/base/img/round_select.png');
                    allimg.attr('src', '/static/base/img/round_select.png');
                    {#                    这里是将删除按钮变高亮显示#}
                    mydel.css('color', 'black');
                    {#                    下面是获取所有价格的方法#}
                    var gprice = $('.gprice');
                    var mynum = $('.mynum');
                    var dum = 0;
                    for (var i = 0; i < gprice.length; i++) {
                        var myprice = (gprice[i].innerHTML).substring(2);
                        var mynumtwo = (mynum[i].innerHTML);
                        var mypricetwo = Number(myprice) * Number(mynumtwo);
                        dum += mypricetwo;
                    }
                    var myprice = $('.myprece');
                    {#                    显示价格并设定小数点位数#}
                    myprice[0].innerHTML = dum.toFixed(2);
                } else {
                    onesrue.attr('src', '/static/base/img/round.png');
                    allimg.attr('src', '/static/base/img/round.png');
                    var myprice = $('.myprece');
                    myprice[0].innerHTML = '0.0';
                    mydel.css('color', '#ccc');
                }
            });
            {#            获取所有商品ID的事件#}
            $('.myright').click(function () {
                {#                应该获取所有的数据ID返回给后端#}
                var allimg = $('.usleft').children('img');
                var arr = getgoodid(allimg);

            });
            mydel.click(function () {
                var allimg = $('.usleft').children('img');
                var arr = getgoodid(allimg);
                $.ajax({
                    type: 'POST',
                    url: 'http://127.0.0.1:8000/axf/delgoods/',
                    data: {'ids':arr},
                    dataType: 'json',
                    traditional:true,
                });
            })
        })
    </script>
{% endblock %}
{% block myheader %}
    <div class="mydel" onclick="window.location.href='http://127.0.0.1:8000/axf/cart/'" >删除</div>
{% endblock %}
{% block content %}
    <div class="contents">
        <div class="mycontent">
            {% for ugood in ugoods %}
                <div class="cartgoods">
                    <div class="uleft">
                        <div class="usleft">
                            <img src="{% static 'base/img/round.png' %}">
                            <span class="goodid" style="display: none">{{ ugood.id }}</span>
                        </div>
                        <div class="usright">
                            <img src="{{ ugood.tgoodid.productimg }}">
                        </div>
                    </div>
                    <div class="uright">
                        <p>{{ ugood.tgoodid.productname }}</p>
                        <p class="gprice">￥：{{ ugood.tgoodid.price }}</p>
                    </div>
                    <div class="cartcontent">
                        <a href="{% url 'axf:goodsub' ugood.tgoodid.id %}">
                            <div class="mycartleft">-</div>
                        </a>
                        <div class="mynum">{{ ugood.tgoodnum }}</div>
                        <a href="{% url 'axf:goodadd' ugood.tgoodid.id %}">
                            <div class="mycartright">+</div>
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div id="mytrue">
            <div class="myleft"><img src="{% static 'base/img/round.png' %}"></div>
            <div class="mycenter">
                <div class="centerleft">金额￥:</div>
                <div class="myprece"></div>
            </div>
            <div class="myright">去结算</div>
        </div>
    </div>

{% endblock %}